/* Automatically generated by wasm2c */
#ifndef PTHREAD_TEST_WASM_H_GENERATED_
#define PTHREAD_TEST_WASM_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;
struct w2c_wasi;
struct w2c_wasi__snapshot__preview1;
extern wasm_rt_memory_t* w2c_env_memory(struct w2c_env*);

typedef struct w2c_pthread__test {
  struct w2c_wasi* w2c_wasi_instance;
  struct w2c_wasi__snapshot__preview1* w2c_wasi__snapshot__preview1_instance;
  /* import: 'env' 'memory' */
  wasm_rt_memory_t *w2c_env_memory;
  u32 w2c_0x5F_stack_pointer;
  u32 w2c_0x5F_tls_base;
  u32 w2c_0x5F_tls_size;
  u32 w2c_0x5F_tls_align;
  wasm_rt_funcref_table_t w2c_T0;
  bool data_segment_dropped_w2c_pthread__test_0x2Etdata : 1;
  bool data_segment_dropped_w2c_pthread__test_0x2Erodata : 1;
  bool data_segment_dropped_w2c_pthread__test_0x2Edata : 1;
} w2c_pthread__test;

void wasm2c_pthread__test_instantiate(w2c_pthread__test*, struct w2c_env*, struct w2c_wasi*, struct w2c_wasi__snapshot__preview1*);
void wasm2c_pthread__test_free(w2c_pthread__test*);
wasm_rt_func_type_t wasm2c_pthread__test_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'wasi' 'thread-spawn' */
u32 w2c_wasi_thread0x2Dspawn(struct w2c_wasi*, u32);

/* import: 'wasi_snapshot_preview1' 'args_get' */
u32 w2c_wasi__snapshot__preview1_args_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'args_sizes_get' */
u32 w2c_wasi__snapshot__preview1_args_sizes_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'clock_time_get' */
u32 w2c_wasi__snapshot__preview1_clock_time_get(struct w2c_wasi__snapshot__preview1*, u32, u64, u32);

/* import: 'wasi_snapshot_preview1' 'fd_close' */
u32 w2c_wasi__snapshot__preview1_fd_close(struct w2c_wasi__snapshot__preview1*, u32);

/* import: 'wasi_snapshot_preview1' 'fd_fdstat_get' */
u32 w2c_wasi__snapshot__preview1_fd_fdstat_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_seek' */
u32 w2c_wasi__snapshot__preview1_fd_seek(struct w2c_wasi__snapshot__preview1*, u32, u64, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_write' */
u32 w2c_wasi__snapshot__preview1_fd_write(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u32);

/* import: 'wasi_snapshot_preview1' 'proc_exit' */
void w2c_wasi__snapshot__preview1_proc_exit(struct w2c_wasi__snapshot__preview1*, u32);

/* import: 'wasi_snapshot_preview1' 'sched_yield' */
u32 w2c_wasi__snapshot__preview1_sched_yield(struct w2c_wasi__snapshot__preview1*);

extern const u64 wasm2c_pthread__test_min_env_memory;
extern const u64 wasm2c_pthread__test_max_env_memory;
extern const u8 wasm2c_pthread__test_is64_env_memory;

/* export: 'memory' */
wasm_rt_memory_t* w2c_pthread__test_memory(w2c_pthread__test* instance);

/* export: '_start' */
void w2c_pthread__test_0x5Fstart(w2c_pthread__test*);

/* export: 'wasi_thread_start' */
void w2c_pthread__test_wasi_thread_start(w2c_pthread__test*, u32, u32);

#ifdef __cplusplus
}
#endif

#endif  /* PTHREAD_TEST_WASM_H_GENERATED_ */
